#!/usr/bin/env bun
/*
 * opencatalog.sh — Sync pending submissions from Upstash Redis to git.
 *
 * Pulls pending submissions from Redis, writes them as candidate files
 * in staging/, and creates a GitHub PR for review. After syncing, marks
 * submissions as "synced" in Redis.
 *
 * This script runs in GitHub Actions (every 2 hours). It can also be run
 * locally if Redis env vars are set.
 *
 * Usage:
 *   bun run scripts/sync-kv.ts                # sync all pending
 *   bun run scripts/sync-kv.ts --dry-run      # show what would be synced
 *   bun run scripts/sync-kv.ts --create-pr    # create a GitHub PR after sync
 *
 * Environment (auto-provisioned by Vercel marketplace):
 *   KV_REST_API_URL — Upstash Redis REST endpoint
 *   KV_REST_API_TOKEN — Upstash Redis auth token
 *   GITHUB_TOKEN — for creating PRs (auto-provided by GitHub Actions)
 */

import { Redis } from "@upstash/redis";
import { writeFile, mkdir, stat } from "node:fs/promises";
import { execSync } from "node:child_process";
import path from "node:path";
import {
  Candidate,
  type Candidate as CandidateType,
  candidateFilePath,
} from "../src/lib/candidate-schema";

const DRY_RUN = process.argv.includes("--dry-run");
const CREATE_PR = process.argv.includes("--create-pr");

function git(args: string[]): string {
  return execSync(`git ${args.join(" ")}`, { encoding: "utf-8", stdio: ["pipe", "pipe", "pipe"] }).trim();
}

async function main() {
  const url = process.env.KV_REST_API_URL;
  const token = process.env.KV_REST_API_TOKEN;
  if (!url || !token) {
    console.error("Redis not configured. Set KV_REST_API_URL and KV_REST_API_TOKEN.");
    process.exit(1);
  }

  const redis = new Redis({ url, token });

  // Get all pending submission IDs
  const submissionIds = (await redis.smembers("pending:queue")) as string[];
  if (submissionIds.length === 0) {
    console.log("No pending submissions in Redis.");
    process.exit(0);
  }

  console.log(`Found ${submissionIds.length} pending submission${submissionIds.length === 1 ? "" : "s"}.\n`);

  const synced: string[] = [];
  const failed: string[] = [];

  for (const id of submissionIds) {
    const raw = await redis.get(`pending:${id}`);
    if (!raw) {
      console.log(`  ✗ ${id}: not found in Redis (stale queue entry)`);
      await redis.srem("pending:queue", id);
      failed.push(id);
      continue;
    }

    const candidateJson = typeof raw === "string" ? JSON.parse(raw) : raw;
    const result = Candidate.safeParse(candidateJson);
    if (!result.success) {
      console.log(`  ✗ ${id}: schema validation failed`);
      for (const issue of result.error.issues.slice(0, 3)) {
        console.log(`      ${issue.path.join(".")}: ${issue.message}`);
      }
      failed.push(id);
      continue;
    }

    const candidate = result.data;
    const stagingPath = candidateFilePath(candidate);
    const fullPath = path.join(process.cwd(), stagingPath);

    // Check if already exists in staging
    try {
      await stat(fullPath);
      console.log(`  → ${candidate.slug}: already in staging, skipping`);
      continue;
    } catch {
      // Good — doesn't exist
    }

    console.log(`  ✓ ${candidate.slug} → ${stagingPath}`);

    if (!DRY_RUN) {
      await mkdir(path.dirname(fullPath), { recursive: true });
      await writeFile(fullPath, `${JSON.stringify(candidate, null, 2)}\n`);

      // Mark as synced in Redis
      await redis.srem("pending:queue", id);
      await redis.del(`pending:${id}`);
      await redis.del(`pending:slug:${candidate.slug}`);
      await redis.set(
        `synced:${id}`,
        JSON.stringify({
          slug: candidate.slug,
          syncedAt: new Date().toISOString(),
          stagingPath,
        }),
      );
    }

    synced.push(candidate.slug);
  }

  console.log("");
  if (DRY_RUN) {
    console.log(`dry run — ${synced.length} would be synced, ${failed.length} failed`);
    process.exit(0);
  }

  console.log(`synced ${synced.length} submission${synced.length === 1 ? "" : "s"}, ${failed.length} failed`);

  // Create PR if requested and there are synced entries
  if (CREATE_PR && synced.length > 0) {
    const branch = `submission/sync-${Date.now()}`;
    const prTitle = `submissions: sync ${synced.length} new candidate${synced.length === 1 ? "" : "s"}`;

    try {
      git(["config", "user.name", "github-actions[bot]"]);
      git(["config", "user.email", "github-actions[bot]@users.noreply.github.com"]);
      git(["checkout", "-b", branch]);
      git(["add", "staging/"]);
      git(["commit", "-m", `${prTitle}\n\nSynced from Upstash Redis pending queue.\n\nCandidates: ${synced.join(", ")}\n\nGenerated by sync-kv.ts`]);
      git(["push", "--set-upstream", "origin", branch]);

      const prBody = `## Synced submissions

${synced.map((s) => `- \`${s}\``).join("\n")}

## Review checklist
- [ ] Each candidate has valid sources
- [ ] Run \`bun run validate:staging\` — passes
- [ ] Run \`bun run enrich\` — probes URLs, fetches stats
- [ ] Run \`bun run promote\` — promotes to curated/
- [ ] Run \`bun run validate && bun run build\` — passes

Generated by sync-kv.ts GitHub Action.`;

      execSync(`gh pr create --title "${prTitle}" --body "${prBody.replace(/"/g, '\\"')}" --label "submission"`, {
        stdio: "inherit",
      });
      console.log(`\n✓ Created PR: ${prTitle}`);
    } catch (err) {
      console.error(`Failed to create PR: ${err}`);
      process.exit(1);
    }
  }

  process.exit(failed.length > 0 ? 1 : 0);
}

main();
